paths:
  incoming: data/incoming
  archive: data/archive
  duckdb: data/potato_breeding.duckdb


file_extensions: [".xlsx", ".xls"]
columns: ["Location", 
          "Experiment Name", 
          "Plot", 
          "Origin", 
          "Name1", 
          "Year", 
          "TUBERSIZE", 
          "EVENESS", 
          "APPEARANCE", 
          "TUBNUMBERS",
          "FFSCAB", 
          "FFDEFECTS", 
          "FFHOLLOWH", 
          "FF_IRS", 
          "EYEDEPTH", 
          "O_A_SCORE", 
          "TUBSHAPE", 
          "SKINCOLOUR", 
          "FLESHCOLOU", 
          "COMMENTS",
          "DRYNESS", 
          "DRYMATTER", 
          "FINALYIELD", 
          "UNIFORMITY", 
          "DSNTGRTN",
          "MEALINESS", 
          "UTILISATIO", 
          "ACB", 
          "OVALL_COOK", 
          "CRISP", 
          "COFLSCOL",
          "ACB24", 
          "FLAVOUR", 
          "CHIPCOLOUR", 
          "HUNTERL", 
          "HUNTERA", 
          "HUNTERB",
          "COOK_COM", 
          "CRISP_YR4", 
          "CRISP_3M8D", 
          "CRISP_3M4D", 
          "CHIP_3M8D",
          "CHIP_3M4D", 
          "HUNTL_3M8D", 
          "HUNTA_3M8D", 
          "HUNTB_3M8D", 
          "HUNTL_3M4D",
          "HUNTA_3M4D", 
          "HUNTB_3M4D", 
          "CHPCOM3M8D", 
          "CHPCOM3M4D", 
          "FFROTS", 
          "CRISP_6M8D", 
          "CRISP_6M4D", 
          "CHIP_6M8D", 
          "CHIP_6M4D", 
          "CHPCOM6M8D",
          "CHPCOM6M4D", 
          "HUNTL_6M8D", 
          "HUNTL_6M4D", 
          "HUNTA_6M8D",
          "HUNTA_6M4D",
          "HUNTB_6M8D", 
          "HUNTB_6M4D", 
          "Average length (mm) >=55", 
          "Average length (mm) >=60", 
          "Average length (mm) >=65",
          "Average length (mm) >=70", 
          "Average length (mm) >=75",
          "Average length (mm) 0-25", 
          "Average length (mm) 25-28",
          "Average length (mm) 28-35", 
          "Average length (mm) 35-40",
          "Average length (mm) 40-45", 
          "Average length (mm) 45-50",
          "Average length (mm) 50-55", 
          "Average length (mm) 55-60",
          "Average length (mm) 60-65", 
          "Average length (mm) 65-70",
          "Average length (mm) 70-75", 
          "Average length (mm) total",
          "Average NIR value total", 
          "Total #",
          "Weight (%) >=75", 
          "Weight (%) 0-25", 
          "Weight (%) 25-28",
          "Weight (%) 28-35", 
          "Weight (%) 35-40", 
          "Weight (%) 40-45",
          "Weight (%) 45-50", 
          "Weight (%) 50-55", 
          "Weight (%) 55-60",
          "Weight (%) 60-65", 
          "Weight (%) 65-70", 
          "Weight (%) 70-75",
          "Weight (g) >=75", 
          "Weight (g) 0-25", 
          "Weight (g) 25-28",
          "Weight (g) 28-35", 
          "Weight (g) 35-40", 
          "Weight (g) 40-45",
          "Weight (g) 45-50", 
          "Weight (g) 50-55", 
          "Weight (g) 55-60",
          "Weight (g) 60-65", 
          "Weight (g) 65-70",  
          "Weight (g) 70-75",
          "Weight (g) total", 
          ">=75 #", 
          ">=75 %", 
          "0-25 #", 
          "0-25 %",
          "25-28 #", 
          "25-28 %", 
          "28-35 #", 
          "28-35 %", 
          "35-40 #", 
          "35-40 %",
          "40-45 #", 
          "40-45 %", 
          "45-50 #", 
          "45-50 %", 
          "50-55 #", 
          "50-55 %",
          "55-60 #", 
          "55-60 %", 
          "60-65 #", 
          "60-65 %", 
          "65-70 #", 
          "65-70 %",
          "70-75 #", 
          "70-75 %", 
          "Average length (mm) >=25", 
          "Average length (mm) >=28",
          "Average length (mm) >=35", 
          "Average length (mm) >=40", 
          "Average length (mm) >=45",
          "Average length (mm) >=50", 
          "Plot size_LT", 
          "Yield total (t/ha)", 
          "Yield >=80 (t/ha)",
          "Yield 0-35 (t/ha)"
        ]
